DROP TABLE IF EXISTS tracks_by_artists CASCADE;

DROP TABLE IF EXISTS user_playlists CASCADE;

DROP TABLE IF EXISTS albums_by_artists CASCADE;

DROP TABLE IF EXISTS playlist_tracks CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS playlists CASCADE;

DROP TABLE IF EXISTS tracks CASCADE;

DROP TABLE IF EXISTS albums CASCADE;

DROP TABLE IF EXISTS artists CASCADE;
